### ISSUE TITLE
Example code does not work on Heroku

### ISSUE THREAD

**Issue by GoodDragon** [alpacahq/samplealgo01#15]
It looks to be example code crashes on Heroku:
```
2019-03-06T20:30:30.039522+00:00 heroku[worker.1]: Starting process with command `python main.py`
2019-03-06T20:30:30.599893+00:00 heroku[worker.1]: State changed from starting to up
2019-03-06T20:30:34.456532+00:00 app[worker.1]: INFO:root:start running
2019-03-06T20:30:34.461121+00:00 app[worker.1]: DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): paper-api.alpaca.markets:443
2019-03-06T20:30:34.566766+00:00 app[worker.1]: DEBUG:urllib3.connectionpool:https://paper-api.alpaca.markets:443 "GET /v1/clock HTTP/1.1" 200 147
2019-03-06T20:30:34.621879+00:00 app[worker.1]: DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): data.alpaca.markets:443
2019-03-06T20:30:34.769843+00:00 app[worker.1]: DEBUG:urllib3.connectionpool:https://data.alpaca.markets:443 "GET /v1/bars/day?symbols=MMM%2CABT%2CABBV%2CACN%2CATVI%2CAYI%2CADBE%2CAMD%2CAAP%2CAES%2CAET%2CAMG%2CAFL%2CA%2CAPD%2CAKAM%2CALK%2CALB%2CARE%2CALXN%2CALGN%2CALLE%2CAGN%2CADS%2CLNT%2CALL%2CGOOGL%2CGOOG%2CMO%2CAMZN%2CAEE%2CAAL%2CAEP%2CAXP%2CAIG%2CAMT%2CAWK%2CAMP%2CABC%2CAME%2CAMGN%2CAPH%2CAPC%2CADI%2CANDV%2CANSS%2CANTM%2CAON%2CAOS%2CAPA%2CAIV%2CAAPL%2CAMAT%2CAPTV%2CADM%2CARNC%2CAJG%2CAIZ%2CT%2CADSK%2CADP%2CAZO%2CAVB%2CAVY%2CBHGE%2CBLL%2CBAC%2CBK%2CBAX%2CBBT%2CBDX%2CBRK.B%2CBBY%2CBIIB%2CBLK%2CHRB%2CBA%2CBKNG%2CBWA%2CBXP%2CBSX%2CBHF%2CBMY%2CAVGO%2CBF.B%2CCHRW%2CCA%2CCOG%2CCDNS%2CCPB%2CCOF%2CCAH%2CKMX%2CCCL%2CCAT%2CCBOE%2CCBRE%2CCBS%2CCELG%2CCNC%2CCNP%2CCTL%2CCERN%2CCF%2CSCHW%2CCHTR%2CCVX%2CCMG%2CCB%2CCHD%2CCI%2CXEC%2CCINF%2CCTAS%2CCSCO%2CC%2CCFG%2CCTXS%2CCLX%2CCME%2CCMS%2CKO%2CCTSH%2CCL%2CCMCSA%2CCMA%2CCAG%2CCXO%2CCOP%2CED%2CSTZ%2CCOO%2CGLW%2CCOST%2CCOTY%2CCCI%2CCSX%2CCMI%2CCVS%2CDHI%2CDHR%2CDRI%2CDVA%2CDE%2CDAL%2CXRAY%2CDVN%2CDLR%2CDFS%2CDISCA%2CDISCK%2CDISH%2CDG%2CDLTR%2CD%2CDOV%2CDWDP%2CDPS%2CDTE%2CDRE%2CDUK%2CDXC%2CETFC%2CEMN%2CETN%2CEBAY%2CECL%2CEIX%2CEW%2CEA%2CEMR%2CETR%2CEVHC%2CEOG%2CEQT%2CEFX%2CEQIX%2CEQR%2CESS%2CEL%2CES%2CRE%2CEXC%2CEXPE%2CEXPD%2CESRX%2CEXR%2CXOM%2CFFIV%2CFB%2CFAST%2CFRT%2CFDX%2CFIS%2CFITB%2CFE%2CFISV%2CFLIR%2CFLS%2CFLR&limit=50&start=2019-01-14&end=2019-03-05 HTTP/1.1" 200 None
2019-03-06T20:30:34.949094+00:00 app[worker.1]: DEBUG:urllib3.connectionpool:https://data.alpaca.markets:443 "GET /v1/bars/day?symbols=FMC%2CFL%2CF%2CFTV%2CFBHS%2CBEN%2CFCX%2CGPS%2CGRMN%2CIT%2CGD%2CGE%2CGGP%2CGIS%2CGM%2CGPC%2CGILD%2CGPN%2CGS%2CGT%2CGWW%2CHAL%2CHBI%2CHOG%2CHRS%2CHIG%2CHAS%2CHCA%2CHCP%2CHP%2CHSIC%2CHSY%2CHES%2CHPE%2CHLT%2CHOLX%2CHD%2CHON%2CHRL%2CHST%2CHPQ%2CHUM%2CHBAN%2CHII%2CIDXX%2CINFO%2CITW%2CILMN%2CIR%2CINTC%2CICE%2CIBM%2CINCY%2CIP%2CIPG%2CIFF%2CINTU%2CISRG%2CIVZ%2CIPGP%2CIQV%2CIRM%2CJEC%2CJBHT%2CSJM%2CJNJ%2CJCI%2CJPM%2CJNPR%2CKSU%2CK%2CKEY%2CKMB%2CKIM%2CKMI%2CKLAC%2CKSS%2CKHC%2CKR%2CLB%2CLLL%2CLH%2CLRCX%2CLEG%2CLEN%2CLUK%2CLLY%2CLNC%2CLKQ%2CLMT%2CL%2CLOW%2CLYB%2CMTB%2CMAC%2CM%2CMRO%2CMPC%2CMAR%2CMMC%2CMLM%2CMAS%2CMA%2CMAT%2CMKC%2CMCD%2CMCK%2CMDT%2CMRK%2CMET%2CMTD%2CMGM%2CKORS%2CMCHP%2CMU%2CMSFT%2CMAA%2CMHK%2CTAP%2CMDLZ%2CMON%2CMNST%2CMCO%2CMS%2CMOS%2CMSI%2CMSCI%2CMYL%2CNDAQ%2CNOV%2CNAVI%2CNKTR%2CNTAP%2CNFLX%2CNWL%2CNFX%2CNEM%2CNWSA%2CNWS%2CNEE%2CNLSN%2CNKE%2CNI%2CNBL%2CJWN%2CNSC%2CNTRS%2CNOC%2CNCLH%2CNRG%2CNUE%2CNVDA%2CORLY%2COXY%2COMC%2COKE%2CORCL%2CPCAR%2CPKG%2CPH%2CPAYX%2CPYPL%2CPNR%2CPBCT%2CPEP%2CPKI%2CPRGO%2CPFE%2CPCG%2CPM%2CPSX%2CPNW%2CPXD%2CPNC%2CRL%2CPPG%2CPPL%2CPX%2CPFG%2CPG%2CPGR%2CPLD%2CPRU%2CPEG%2CPSA%2CPHM%2CPVH%2CQRVO%2CPWR%2CQCOM%2CDGX%2CRRC%2CRJF%2CRTN%2CO%2CRHT%2CREG%2CREGN%2CRF%2CRSG&limit=50&start=2019-01-14&end=2019-03-05 HTTP/1.1" 200 None
2019-03-06T20:30:35.124125+00:00 app[worker.1]: DEBUG:urllib3.connectionpool:https://data.alpaca.markets:443 "GET /v1/bars/day?symbols=RMD%2CRHI%2CROK%2CCOL%2CROP%2CROST%2CRCL%2CCRM%2CSBAC%2CSCG%2CSLB%2CSTX%2CSEE%2CSRE%2CSHW%2CSPG%2CSWKS%2CSLG%2CSNA%2CSO%2CLUV%2CSPGI%2CSWK%2CSBUX%2CSTT%2CSRCL%2CSYK%2CSTI%2CSIVB%2CSYMC%2CSYF%2CSNPS%2CSYY%2CTROW%2CTTWO%2CTPR%2CTGT%2CTEL%2CFTI%2CTXN%2CTXT%2CTMO%2CTIF%2CTWX%2CTJX%2CTMK%2CTSS%2CTSCO%2CTDG%2CTRV%2CTRIP%2CFOXA%2CFOX%2CTSN%2CUDR%2CULTA%2CUSB%2CUAA%2CUA%2CUNP%2CUAL%2CUNH%2CUPS%2CURI%2CUTX%2CUHS%2CUNM%2CVFC%2CVLO%2CVAR%2CVTR%2CVRSN%2CVRSK%2CVZ%2CVRTX%2CVIAB%2CV%2CVNO%2CVMC%2CWMT%2CWBA%2CDIS%2CWM%2CWAT%2CWEC%2CWFC%2CWELL%2CWDC%2CWU%2CWRK%2CWY%2CWHR%2CWMB%2CWLTW%2CWYN%2CWYNN%2CXEL%2CXRX%2CXLNX%2CXL%2CXYL%2CYUM%2CZBH%2CZION%2CZTS&limit=50&start=2019-01-14&end=2019-03-05 HTTP/1.1" 200 None
2019-03-06T20:30:35.401433+00:00 app[worker.1]: Traceback (most recent call last):
2019-03-06T20:30:35.401457+00:00 app[worker.1]: File "main.py", line 5, in <module>
2019-03-06T20:30:35.401637+00:00 app[worker.1]: algo.main()
2019-03-06T20:30:35.401657+00:00 app[worker.1]: File "/app/samplealgo/algo.py", line 208, in main
2019-03-06T20:30:35.401931+00:00 app[worker.1]: price_df = prices(Universe)
2019-03-06T20:30:35.401951+00:00 app[worker.1]: File "/app/samplealgo/algo.py", line 60, in prices
2019-03-06T20:30:35.402120+00:00 app[worker.1]: return _get_prices(symbols, end_dt)
2019-03-06T20:30:35.402139+00:00 app[worker.1]: File "/app/samplealgo/algo.py", line 50, in _get_prices
2019-03-06T20:30:35.402296+00:00 app[worker.1]: return barset.df
2019-03-06T20:30:35.402316+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/alpaca_trade_api/entity.py", line 102, in df
2019-03-06T20:30:35.402521+00:00 app[worker.1]: df = bars.df.copy()
2019-03-06T20:30:35.402852+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/alpaca_trade_api/entity.py", line 84, in df
2019-03-06T20:30:35.403058+00:00 app[worker.1]: df.index * 1e9, utc=True,
2019-03-06T20:30:35.403079+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/pandas/core/ops.py", line 176, in invalid_op
2019-03-06T20:30:35.403304+00:00 app[worker.1]: "{typ}".format(name=name, typ=type(self).__name__))
2019-03-06T20:30:35.403333+00:00 app[worker.1]: TypeError: cannot perform __mul__ with this index type: Index
2019-03-06T20:30:35.559872+00:00 heroku[worker.1]: State changed from up to crashed
2019-03-06T20:30:35.575397+00:00 heroku[worker.1]: State changed from crashed to starting
2019-03-06T20:30:35.545925+00:00 heroku[worker.1]: Process exited with status 1
```

Also notice that screenshots are missing from:
https://docs.alpaca.markets/example-algos/sp500-buy-dip/#heroku-free

**Comment by jeichenseerNRX** [comment]
This is surely the same issue as #12 
Try the fix recommended by @cujo0072
