### ISSUE TITLE
TypeError: cannot perform __mul__ with this index type: Index

### ISSUE THREAD

**Issue by SaviourSelf** [alpacahq/samplealgo01#7]
Cloned the repo and added my keys, and I cannot either backtest or run the trader on the paper api endpoint without this exception.

Stack trace: 
```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    algo.main()
  File "/Users/ss/alpaca2/samplealgo01/samplealgo/algo.py", line 210, in main
    price_df = prices(Universe)
  File "/Users/ss/alpaca2/samplealgo01/samplealgo/algo.py", line 62, in prices
    return _get_prices(symbols, end_dt)
  File "/Users/ss/alpaca2/samplealgo01/samplealgo/algo.py", line 52, in _get_prices
    return barset.df
  File "/usr/local/lib/python3.6/site-packages/alpaca_trade_api/entity.py", line 102, in df
    df = bars.df.copy()
  File "/usr/local/lib/python3.6/site-packages/alpaca_trade_api/entity.py", line 84, in df
    df.index * 1e9, utc=True,
  File "/usr/local/lib/python3.6/site-packages/pandas/core/ops.py", line 173, in invalid_op
    "{typ}".format(name=name, typ=type(self).__name__))
TypeError: cannot perform __mul__ with this index type: Index
```

**Comment by SaviourSelf** [comment]
Resolving. Issue was resolved with PR https://github.com/alpacahq/alpaca-trade-api-python/pull/45/files
