### ISSUE TITLE
Crashes on empty bar data

### ISSUE THREAD

**Issue by kaiwen180** [alpacahq/samplealgo01#9]
When data is empty, the sample crashes.  For example, ANDV:
{"ANDV":[]}

DEBUG:urllib3.connectionpool:https://data.alpaca.markets:443 "GET /v1/bars/day?symbols=ANDV&limit=50&start=2018-11-20&end=2019-1-9 HTTP/1.1" 200 11
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    algo.main()
  File "/Users/kaiwenlin/Downloads/dev/trading/samplealgo01/samplealgo/algo.py", line 209, in main
    price_df = prices(Universe)
  File "/Users/kaiwenlin/Downloads/dev/trading/samplealgo01/samplealgo/algo.py", line 60, in prices
    return _get_prices(symbols, end_dt)
  File "/Users/kaiwenlin/Downloads/dev/trading/samplealgo01/samplealgo/algo.py", line 50, in _get_prices
    return barset.df
  File "/Users/kaiwenlin/.local/share/virtualenvs/samplealgo01-yx1O27NF/lib/python3.6/site-packages/alpaca_trade_api/entity.py", line 102, in df
    df = bars.df.copy()
  File "/Users/kaiwenlin/.local/share/virtualenvs/samplealgo01-yx1O27NF/lib/python3.6/site-packages/alpaca_trade_api/entity.py", line 84, in df
    df.index * 1e9, utc=True,
  File "/Users/kaiwenlin/.local/share/virtualenvs/samplealgo01-yx1O27NF/lib/python3.6/site-packages/pandas/core/ops.py", line 176, in invalid_op
    "{typ}".format(name=name, typ=type(self).__name__))
TypeError: cannot perform __mul__ with this index type: Index

**Comment by kaiwen180** [comment]
Fix: update Pipfile

[packages]
alpaca-trade-api = "==0.24"
